# Generated by Django 4.2 on 2023-04-19 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('withdrawal_threshold', models.PositiveIntegerField()),
                ('commission', models.DecimalField(decimal_places=2, max_digits=2)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('reference_link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MarketerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketer_product', to='Marketing_System.marketer')),
            ],
            options={
                'verbose_name': 'Sell',
                'verbose_name_plural': 'Sales',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('marketers', models.ManyToManyField(related_name='products', through='Marketing_System.MarketerProduct', to='Marketing_System.marketer')),
            ],
        ),
        migrations.AddField(
            model_name='marketerproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketer_product', to='Marketing_System.product'),
        ),
        migrations.AlterUniqueTogether(
            name='marketerproduct',
            unique_together={('marketer', 'product')},
        ),
    ]
