# Generated by Django 4.2 on 2023-04-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing_System', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketer',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='product',
            name='marketer',
        ),
        migrations.AddField(
            model_name='product',
            name='marketer',
            field=models.ManyToManyField(related_name='products', to='Marketing_System.marketer'),
        ),
    ]
