# Generated by Django 4.2 on 2023-04-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing_System', '0002_alter_marketer_balance_remove_product_marketer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='marketer',
        ),
        migrations.AddField(
            model_name='marketer',
            name='products',
            field=models.ManyToManyField(related_name='marketers', to='Marketing_System.product'),
        ),
    ]
