# Generated by Django 4.2 on 2023-04-19 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing_System', '0003_remove_product_marketer_marketer_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketer',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='marketer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='Marketing_System.marketer'),
        ),
    ]
