# Generated by Django 4.2 on 2023-04-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing_System', '0004_remove_marketer_products_product_marketer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='marketer',
        ),
        migrations.AddField(
            model_name='product',
            name='marketer',
            field=models.ManyToManyField(related_name='products', to='Marketing_System.marketer'),
        ),
    ]
