# Generated by Django 4.2 on 2023-04-19 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing_System', '0005_remove_product_marketer_product_marketer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='marketer',
            new_name='marketers',
        ),
    ]
