# Generated by Django 4.2 on 2023-04-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing_System', '0006_rename_marketer_product_marketers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketer',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='marketer',
            name='commission',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
